language:
  php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --dev --no-interaction --prefer-source
  - phpenv rehash

script:
  - vendor/bin/phpunit --configuration tests/phpunit.xml --testdox tests/

matrix:
  allow_failures:
    - php: hhvm

notifications:
  irc:
    channels:
      - "irc.freenode.org#php-respect"
    use_notice: true
