sudo:
  false

language:
  php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

cache:
  directories:
  - vendor

before_script:
  - composer install --dev --no-interaction --prefer-source
  - phpenv rehash

script:
  - vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover=coverage.clover --testdox tests/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

notifications:
  irc:
    channels:
      - "irc.freenode.org#php-respect"
    use_notice: true
